# 参考文档
# https://docs.projectdiscovery.io/tools/nuclei/running#nuclei-config
# https://github.com/projectdiscovery/nuclei/issues/472

proxy: http://127.0.0.1:8080

# 所有 HTTP 请求中要包含的标头
# header:
#   - 'X-BugBounty-Hacker: h1/geekboy'

# 基于目录的模板执行
# templates:
#   - cves/
#   - vulnerabilities/
#   - misconfiguration/

# 基于标签的模板执行
# tags: exposures,cve

# 模板过滤器
# tags: exposures,cve
# author: geeknik,pikpikcu,dhiyaneshdk
# severity: critical,high,medium

# 模板允许列表
include-tags: 
  - fuzz
  - devops
  - cloud
  - default-login
include-templates: # Template based inclusion (allows overwriting nuclei-ignore list)
  - dns/spf-record-detect.yaml
  - http/default-logins/
  - network/default-login/
  - javascript/default-logins/
  - ssl/ssl-dns-names.yaml
  - dns/dns-waf-detect.yaml
  - http/technologies/waf-detect.yaml
  - http/technologies/springboot-actuator.yaml
  - http/misconfiguration/springboot/springboot-heapdump.yaml
  - http/misconfiguration/jolokia/jolokia-list.yaml
  - http/misconfiguration/springboot/spring-eureka.yaml
  - http/technologies/nacos-version.yaml
  - http/cves/2021/CVE-2021-29441.yaml
  - http/cves/2021/CVE-2021-29442.yaml
  - http/misconfiguration/nacos-authentication-bypass.yaml
  - http/misconfiguration/unauthenticated-nacos-access.yaml
  - http/exposures/apis/swagger-api.yaml
  - http/exposures/configs/git-config.yaml
  - http/misconfiguration/druid-monitor.yaml
  - http/technologies/shiro-detect.yaml
  - http/cves/2021/CVE-2021-31805.yaml
  - http/technologies/weblogic-detect.yaml
  - http/cves/2014/CVE-2014-4210.yaml
  - http/cves/2017/CVE-2017-10271.yaml
  - http/cves/2017/CVE-2017-3506.yaml
  - http/cves/2018/CVE-2018-2894.yaml
  - http/cves/2019/CVE-2019-2725.yaml
  - http/cves/2019/CVE-2019-2729.yaml
  - http/cves/2020/CVE-2020-14750.yaml
  - http/cves/2020/CVE-2020-14882.yaml
  - http/cves/2020/CVE-2020-14883.yaml
  - http/cves/2020/CVE-2020-2551.yaml
  - http/cves/2020/CVE-2020-2733.yaml
  - http/cves/2022/CVE-2022-21371.yaml
  - http/default-logins/weblogic/weblogic-weak-login.yaml
  - http/exposed-panels/weblogic-uddiexplorer.yaml
  - network/cves/2018/CVE-2018-2628.yaml
  - network/cves/2018/CVE-2018-2893.yaml
  - network/detection/weblogic-iiop-detect.yaml
  - network/detection/weblogic-t3-detect.yaml
  - network/exposed-zookeeper.yaml
  - network/detection/samba-detect.yaml
  - network/detection/rdp-detect.yaml
  - http/exposures/backups/zip-backup-files.yaml

# 模板拒绝列表
exclude-tags: 
  - xss
  - ssh
  - dos
  - osint
  - c2
  - malware
  - bokbot
  - trojan 
  - creds-stuffing
  - token-spray
  - local
  - wordpress
  - dvwa
exclude-templates: # Template based exclusion
  - config
  - file
  - profiles
  - dns\caa-fingerprint.yaml
  - dns\nameserver-fingerprint.yaml
  - http\miscellaneous\external-service-interaction.yaml
  - http\miscellaneous\google-floc-disabled.yaml
  - http\miscellaneous\old-copyright.yaml
  - http\miscellaneous\rdap-whois.yaml
  - http\misconfiguration\http-missing-security-headers.yaml
  - http\misconfiguration\httponly-cookie-detect.yaml
  - http\technologies\spring-detect.yaml
  - http\technologies\tech-detect.yaml
  - http\vulnerabilities\generic\request-based-interaction.yaml
  - javascript\detection\ssh-auth-methods.yaml
  - javascript\enumeration\ssh-cbc-mode-ciphers.yaml
  - javascript\enumeration\ssh-diffie-hellman-logjam.yaml
  - javascript\enumeration\ssh-password-auth.yaml
  - javascript\enumeration\ssh-server-enumeration.yaml
  - javascript\enumeration\ssh-sha1-hmac-algo.yaml
  - javascript\enumeration\ssh-weak-algo-supported.yaml
  - javascript\enumeration\ssh-weak-mac-algo.yaml
  - javascript\enumeration\ssh-weakkey-exchange-algo.yaml
  - ssl\deprecated-tls.yaml
  - ssl\detect-ssl-issuer.yaml
  - ssl\tls-version.yaml
  
# 速率限制配置
bulk-size: 50
concurrency: 50
rate-limit: 500

# Gihub actions config
# concurrency: 150
# rate-limit: 2000
# retries: 1
# timeout: 2

# Nuclei CLI flags
# include-rr: false
# json: false
# no-meta: false
# update-directory: $HOME/
update-templates: false

# 禁用nuclei程序与模板更新
disable-update-check: true

# 禁用反连检测平台，同时排除基于反连检测的模板
## 反连检测的误报率相对较高，并且内网环境下不适用，可按需启用
no-interactsh: true
silent: true

# 显示扫描进度统计情况
stats: true

# 关闭云上传
cloud-upload: false

no-max-host-error: true

timeout: 5

markdown-export: markdown-export
report-db: report-db
